[general]
import = ["~/dotfiles/.config/alacritty/themes/calorie.toml"]

[env]
TERM = "alacritty"

[font]
size = 18.0
builtin_box_drawing = true

[font.normal]
family = "HackGen"
style = "Regular"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Command"

[mouse]
hide_when_typing = true

[window]
startup_mode = "SimpleFullscreen"
decorations = "None"
option_as_alt = "Both"
opacity = 1.0

[cursor]
thickness = 0.25

[scrolling]
history = 0
